// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecipeBook.Data.Entities
{
    public partial class Ingredient
    {
        public int InId { get; set; }
        public int InMeid { get; set; }
        public int InReid { get; set; }
        public int InQuantity { get; set; }
        public string InName { get; set; }
    }
}