// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecipeBook.Data.Entities
{
    public partial class Measurement
    {
        public int MeId { get; set; }
        public string MeName { get; set; }
        public string MeAbbreviation { get; set; }
    }
}