// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecipeBook.Data.Entities
{
    public partial class Recipe
    {
        public int ReId { get; set; }
        public int? ReCookTime { get; set; }
        public int ReIsGood { get; set; }
        public int? RePrepTime { get; set; }
        public int? ReServings { get; set; }
        public DateTime ReDateAdded { get; set; }
        public string ReDirections { get; set; }
        public string ReName { get; set; }
        public string ReNotes { get; set; }
        public string ReTips { get; set; }
        public string ReUrl { get; set; }
    }
}